### ISSUE TITLE
Compile java classes into jar file using Eclipse

### ISSUE THREAD

**Issue by filippobottega** [bazaarvoice/jolt#115]
Hi,
  I'm trying to compile JOLT with Eclipse. I need to export a jar file and then I'd like to convert it with IKVM to get a .NET callable dll.
  I need a little documentation with steps to build the jar file with all needed references.

  Thank you for your help,
    best regards, Filippo.

**Comment by milosimpson** [comment]
Sorry, I don't really know much about Eclipse.  I have been on Intellij since version 3.0.

So, you want a single Jar with Jolt and all of it's dependencies, so that you can run it thru a Java to .Net compiler?

If so, I think the Maven Shade plugin is your best bet.  
http://www.avajava.com/tutorials/lessons/how-do-i-build-a-jar-file-that-contains-its-dependencies.html
http://maven.apache.org/plugins/maven-shade-plugin/examples/includes-excludes.html

The Shade plugin will build a single Jar that includes all the dependencies.   I would add it to the jolt/complete/pom.xml file.
