### ISSUE TITLE
Support for escaping dot (.) character

### ISSUE THREAD

**Issue by manoj-chavan** [bazaarvoice/jolt#134]
I've a spec which looks something like below:

"tcp": "NetworkProtocol.TCP"

Here I'm expecting "NetworkProtocol.TCP" to be a single attribute name which has a dot in it.

I tried escaping dot and giving it in single quotes, but doesn't seem to work.

**Comment by milosimpson** [comment]
Sorry, Jolt currently does not have any support for escaping any of its wildcard characters.

**Comment by qwelyt** [comment]
I'm a bit curious if this is being worked on.
Currently trying to convert JSON generated by Jackson, which includes tags like `"@class" : "com.company.my.path.class"` in order to be able to map it back to the correct object. As `@` is on of Jolts wildcard, we need to do a string replace to get rid of them before transformation, then add them again so the object mapper can read it correctly. Simply escaping them in Jolt would seem like an easier alternative (and faster)

**Comment by milosimpson** [comment]
Not at the moment.   All the parsing Jolt does to turn the Json spec into actionable items was rolled by hand.   

I have twice tried to use / wrap my head around ANTLR as a parser tool and did not make any headway.

I found parboiled and have a branch were I have has some moderate success with it.

**Comment by LinarKulinar** [comment]
I did not immediately understand that you need to escape with a double backslash.
The commit comment states:
```
* "data.ref.local" --> { "data" : { "ref" : { "local" : X } } }
* "data.ref\.local" --> { "data" : { "ref.local" : X } }
```
But it only worked for me
```
* "data.ref\\.local" --> { "data" : { "ref.local" : X } }
```
