### ISSUE TITLE
Adding calculated values to output.json

### ISSUE THREAD

**Issue by qwelyt** [bazaarvoice/jolt#147]
This is more of a question of what JOLT is capable of rather than an issue.

Say that we have the following JSON
```json
{
    "value1": "2",
    "value2": "3"
}
```

And now say that we want to perform a transformation on these, we can go with a simple addition (but in reality we might have to perform some heavy calculation and other operations based on it all) and want the output to be something like
```json
{
   "calculated": "5"
}
```

Is this something that JOLT is able to do? Or is it more meant to "shuffle data around"?

**Comment by milosimpson** [comment]
It is more "shuffle data around".

The idea is to use the core Jolt transforms (shift, remove, default, etc) to restructure you data as needed, then implement your "custom" logic either afterwards or as custom Java Transforms that can be run and intermixed with (shift, remove, default, etc).

**Comment by qwelyt** [comment]
To give this some context: We use event sourcing in our product. We save our events as json data. We then map that with an object mapper when we read our events.
We were looking to use Jolt to be able to handle updates of events. Ie, we keep our old JSON in our event store and then just transform them into the new form when read. While not an issue today, we _know_ that the day will come when we have to add fields that contains values that has to be calculated, and not just hard coded values. We also have a performance demand. Any transform may not take more than 0.01s as we have a couple of hundred thousand events that need to be transformed at runtime.
So that is the background to my question and research regarding if Jolt is the right choice for us so we can skip the whole JSON -> XML + XSLT -> JSON dance.

As I've got pretty much no experiance what so ever with Jolt, do you have any example where you have done any kind of Jolt transforms with calculations? Anything at all would really be appreciated.

**Comment by milosimpson** [comment]
The stock transforms provided by Jolt don't do any "calculations".   They are really just to "move data" around / adjust the format of the data.  The spirit of the project is, leverage it for what it can do, an then implement the rest of your business logic.

Derived values, calculations, fixing Date formats, etc is all "custom" from Jolt's perspective.   We implement things like that as Java code which implements Jolt's Transform interface, so we can run them as part of the chain of transforms.  It is nice to include the custom transforms in the chain, so that we can unit test the "whole transform", aka given this input, the output document should look like X.   We have a nice tool for "diffy" Json, called Diffy.

We use Jolt to transform our backend Json data format to match our existing api contract : https://developer.bazaarvoice.com/docs/read/conversations/reviews/display.  

For instance, the Jolt transform that handles reviews has 13 "operations" in it, all the "stock" Jolt ones (remove, cardinality, shift, default) and then 7 other custom Java transforms that live in the Api project and not in Jolt.

Performance wise : across a cluster of machines we are doing 2k transforms a second.  
* 95th percentile transform time is 0.75 ms.
* 75th is 0.15 ms
* Median is 0.04 ms

I am pretty sure that the 95th percentile time is dominated by our "custom" Java Transforms (we have one big hairy one in particular), but I don't really know.  For us the, transforms are sufficiently fast, as our runtime is dominated by our backend calls to get data.

**Comment by qwelyt** [comment]
I did it like this in my basic tests:
Have a spec that uses the operation `default` to input an empty field, cast the transformed object you get from `Chainr.transform` to a `LinkedHashMap`, get the key that was entered, use `.put` to input the calculated value. And finally use `JsonUtils.toJsonString` to turn the `LinkedHashMap` into a json string again.
With this method, I tried to use a small subset of our data (50000 entries), our boot time (as we do the transformation at boot only) increased with 22 seconds (from ~35s to ~57s). With 3 chained `default` operations, it increased with 37 seconds (~35s to ~72s). 
In a production environment this is not that big of a deal, those rarely get rebooted and it's done at night. Developer environments however will suffer. So I'm a bit concerned about the speed of this.

I have two different questions and perhaps they should be their own issues, but I'll ask them here for brevity and if they should be issues I'd be happy to make them.
So,
* Why does `Chainr.transform` return `Object` instead of `LinkedHashMap` ? Is it because the structure of Json (ie. { "val1": "string", "val2": {"nested1": "string"} }? But why not return a 'real' type whenever you can? Otherwise there is quite a bit of casting before you can access a nested value. Consider this:
 ```java
final Map map = (LinkedHashMap) transformed;
map.put("calculated", ((LinkedHashMap)((LinkedHashMap) map.get("level1")).get("level2)).get("value));
```
Which is an actual example from one of my tests as much of our information is nested (it's natural when objects contains objects I guess).

* How does Jolt handle variable depth of a field?
Say that we are looking to change how the object `TimeBox` looks.
First, it looked like this `{ "from": "2015-09-26", "to":"2015-09-27" }`. Then due to some reason, we want to add a field so it looks like `{ "from": "2015-09-26", "to":"2015-09-27" , "valid":"true"}`.
This object can be nested at different depths of other objects, like this
   ```json
{ "Employment": { 
  "TimeBox" : { 
    "from": "2015-09-26", 
    "to":"2015-09-27" 
  }
} }
```
    ```json
{ "Person": { 
    "firstName":"John", 
    "lastName":"Smith" , 
    "household": {
      "name": "Smith", 
      "TimeBox": { 
        "from": "2015-09-26", 
        "to":"2015-09-27" 
      }
    }
  } }
```
Can Jolt handle this variation of depth for the object somehow? Or do you have to have a separate spec for each type of Json to change the same thing (ie, one spec for `Employment`, one spec for `Person`, etc)?

**Comment by milosimpson** [comment]
So couple of things.
* Are you making a new Chainr object for each of the 50k items to transform?   Should make one, and reuse it.
* The out-of-the-box operations are safe to use multi-threaded, so you might be able to reduce you boot time by throwing more threads at it.
* Chainr returns an Object because it is valid for JSON to be a {} or a [] at the top level.   Although default does not work with top level Array data...
* Re lots of nasty casting: Yes there is.  See https://github.com/bazaarvoice/jolt/blob/master/jolt-core/src/main/java/com/bazaarvoice/jolt/utils/JoltUtils.java  navigate and navigateSafe methods.
    * those help to contain the casting
* You should probably have a different spec for each "type" of Json you need to process.  It is what we do.   You can maybe get away with reusing spec across types, but I think it would bite you in the long run.

**Comment by milosimpson** [comment]
Also, your usecase doesn't seem to playing to Jolt's primary strength, which is the "shift" operation, which can facilitate radical changes in document format.

Seems like your use case is to add incremental fields.   

You other option I can see is to use a templating language like FreeMarker.

**Comment by qwelyt** [comment]
* Baseline: 38 seconds (3s increase) with the following:
```java
final String event = resultSet.getString("payload");
final Object eventJson = JsonUtils.jsonToObject(event);
final String jsonString = JsonUtils.toJsonString(eventJson));
```
* I do create new Chainr objects for each as I wanted to see how well Jolt could handle  using a different `spec` for each event. 

* My use-case is this: We use event-sourcing. As such we have a  lot of events in our database. With event-sourcing comes a "minor" drawback: How do you handle changes to events? What we found is that we have 3 options.
  1. Read up the database, make changes to all our events, put the changed events back. This is a "lossy migration" as data can be removed and  it will be lost forever.
  2. Support all versions of an event. This quickly litter the code as you will soon find yourself with X number of versions of an event, and all have to be supported and operate with each other without hiccup.
  3. Don't ever change stored event, and only support one version. This means that when you read the event, you have to check it to see what version it is and transform it into the new form so it can be mapped with an ObjectMapper.

  We chose option 3 and are now looking for frameworks that support  this, and hoping that Jolt could be of help.

* We don't really want to just "add incremental fields". I only chose to add fields for testing. But actual cases might well need to use the `shift` operator and the `remove` operator. 

* We have several different type of events. These events contain other objects. If we were to change one of the objects that these events contain, it would potentially mean that we would have to create a new spec for each event that contains this one object. This instead of having one spec that every event can call upon to change that part of its Json. So, we would much rather see if it were possible to do it the "one-spec-for-many" way.

**Comment by milosimpson** [comment]
So here is what I think you should do, having read the comment above and this one https://github.com/bazaarvoice/jolt/issues/135#issuecomment-146115336.

# Build a library of Jolt transforms for each low level "type of object" you have.
#* from your example it would be an "employment" object
#* The "type" specific Jolt transforms handle the version issue you mentioned.
# Build a library of Jolt Transforms for each "high" level type of object you have.
#* High level means it can contain nested objects.
#* Write an implementation of SpecDriven Transform so that the "high level" object can be described declaritivlely, and then call Jolt from inside Jolt.

Example:
```
{
    "class": "my.cass",
    "version": 1,
    "employment": {
        "version": 3,
        "closed": false,
        "from": "2015-08-17",
        "timeBoxId": {
            "id": "8b51957d-a348-4302-a079-ddc4a3623a34"
        },
        "to": null,
        "toBeRemoved": false,
        "value": {
            "extent": "100",
            "form": "PERMANENT_EMPLOYMENT",
            "resource": false
        }
    }
}
```



In the comment on issue 135, you define an "employment" object.

**Comment by qwelyt** [comment]
Oh, thank you very much for this! Trying to implement it atm and a thought occured.

Say we have an object at `v1`. This gets upgraded according to the third spec (first default operation in your example). Let's say it gets upgraded to `v2`. All fine. We now see the need to introduce a third version. We now face the dilemma that we have both `v1` and `v2` stored somewhere, so we still have to handle both of them. In our spec for upgrading, we now have to make adjustments to both `1` and `2`. Going down the line to say `v37`, this can become quite the headache.

 One option I see with this is to just loop the transformation 36 times so it passes through all the stages. But given that a lot of other transformations might take place as well (assuming we operate on a high level object) things can take a very long time to do.

Another solution I see is to splice it up. Do the low level first, then do the version shifting, after all that is done, clean it up with the unboxing spec. That way to get rid of the surrounding transformations in the midst of it.

This might not be optimal, but I would like to know your thoughts about it. How should/would you do such migrating steps?

**Comment by milosimpson** [comment]
So to restate the problem, transforming an object thru many version has the following issues / potential issues.
* A transform at a time, could take a while.
* Transforming one version to the next, might not actually work (if the version are badly designed).
** `v1` had a field.  `v2` got rid of it.  `v3` brought it back.

Being the pragmatist that I am:  I say
* Stick with a version at a time approach, until it become a performance problem
* Then figure out a way to handle many version jumps at the same time.

To support this the InceptionTransform could be changed to look like the following.  Basically, specify an Array or Transforms to run. :
```
[
    {
        "operation": "com.qwetly.InceptionTransform",
        "spec": {
                        // lookup the address object, run the Jolt Transform /transforms/address.jolt 
                        //   and replace the original with the updated version
            "data.address" : [ "/address1to2.jolt", "/address2to3.jolt" ]
            "employment" : [ "/employment1to5.jolt", "/employment5to6.jolt", "/employment6to8.jolt" ]
        }
    },
        ... 
        // do other transforms as needed to migrate the high level object 
        // to the most recent version, similar to the low level ones.
]
```

By using an array of Transforms you have the ability to leverage simple single version Transforms, as well as ones where you can handle a bunch of different versions at the same time (required for the degegerate `v1` has a field, `v2` does not, `v3` has it again).

To be really slick you could come up with some naming convention so that it just finds all Transforms for an object automatically.  I.e.
```
"data.address" : "/address*.jolt" 
```

Just FYI, company is in the eCommerce business, and right now it is crunch time to get stuff done before code freeze for Black Friday.   So, I don't have much time to spend on Jolt right now.   Ideally things free up a bit after early November.   Would like to look into the Shiftr not passing null issue, and at least fix the ability to escape output "."s.   The escaping "@" on the LHS of the Shiftr spec, I think will be harder.
