### ISSUE TITLE
could it be that JOLT is >too< fast and >too< parsimonious w/ object creation on heap so no GC's occur ?

### ISSUE THREAD

**Issue by buildlackey** [bazaarvoice/jolt#305]
Hello, Jolt team:
this is not so much an issue, as a sanity check (if you have time) to see if you think my strategy for benchmarking the object creation overhead of your library is acceptable for our production use.

So far the numbers are actually so good that I have trouble believing them.   I have asked the original question on stack overflow, and if it is OK I will just post a link to that:
 http://stackoverflow.com/questions/41582271/no-garbage-collections-are-reported-in-logs-although-our-benchmark-program-crea

My benchmark shows about 200k average transformation PER SECOND.  Pretty darn good. Just want to make sure I am measuring GC's correctly (hence the question above).  If you have time to comment I thank you very much in advance !  /chris

**Comment by milosimpson** [comment]
## Make your test harder for the JVM

I think that the JVM may being really really clever, and allocating "everything on the stack".

See the 2nd Answer here:
http://softwareengineering.stackexchange.com/questions/65281/stack-and-heap-memory-in-java

This section:
"JVMs can use a technique called escape analysis, by which they can tell that certain objects remain confined to a single thread for their entire lifetime, and that lifetime is bounded by the lifetime of a given stack frame. Such objects can be safely allocated on the stack instead of the heap. Even better, for small objects, the JVM can optimize away the allocation entirely and simply hoist the object's fields into registers."

To force the Input Json and the Output Json to be on the Heap (to give GC something to do), you need to force the data to cross thread boundaries.

Have a thread that is generating the input Json submit it to a ThreadPool which then processes it.    Have the transform worker threads, put the output Json in a Queue, and drain it from a "processing" thread.

## Memory Usage of Jolt
The data-structures and objects that the Jolt spec are processed into are immutable.  
The default and remove transforms operate against their input data, and do not use / make any per call processing datastructures.

The shift transform makes 2 datastructures per call.
1) A "stack" (ArrayList) that is used to keep track of the path current path in the Json & Spec parallel tree walk.   It is used to power the wildcards (&, @).  
See https://github.com/bazaarvoice/jolt/blob/557a9efccf1847498c056c7c122d860ec00aec93/jolt-core/src/main/java/com/bazaarvoice/jolt/common/tree/WalkedPath.java

A new WalkedPath object is created on each shift transform call, but its the kind of thing the JVM would allocate on the Stack rather than the heap, because it does not live past the transform call, and is not visible outside the scope of the transform.

2) Output objects.
When shift runs it makes and populates a new "hydrated" json object.
Example, say this is a line in a shift spec.
```
"max":   "SecondaryRatings.quality.Range",
```
If it matched, then shift will create 3 new LinkedHashMaps.
1) outer most map, to contain key SecondaryRatings
2) SecondaryRatings map to contain key "quality"
3) "quality" map to contain key "Range"

LinkedHashMaps are used because even tho the JSON spec says that the incoming order of JSON map data does not matter, in practice it tends too.

If you use the default Jolt tools to turn your Json Strings into Hydrated objects, then you are using LinkedHashmaps.   That means that when Shift iterates over the intput Maps the traversal matchs what the human saw, and thus the output Json is also more in line with what humans expect.

**Comment by milosimpson** [comment]
@buildlackey any update, now I am curious about the GC results.

**Comment by buildlackey** [comment]
Thanks, Milo - I haven't tried anything after the excellent answer you gave.. I posted the summary to stack overflow and linked back to this issue.    We will continue with our P.O.C.. but so far, Jolt looks great.  thanks for releasing it ;^)
