### ISSUE TITLE
How to use modify overwrite with an explicity Array index

### ISSUE THREAD

**Issue by dbgrey44** [bazaarvoice/jolt#326]
There seems to be some issue with modify overwrite operation. My aim is to overwrite a specific value down the array. But I am not able to traverse down to the specific array element.

Here is the input JSON, I am providing 
`{
	"test_array": [
		{
			"id": 1
		},
		{
			"id": 2
		}
	]
}`

And here is the Transformation spec I am using
`[
  {
    "operation": "modify-overwrite-beta",
    "spec": {
      "test_array": {
        "0": {
          "id": 22
        }
      }
    }
  }
]`

The desired output is 
`{
  "test_array" : [ {
    "id" : 22
  }, {
    "id" : 2
  } ]
}`

but the output that is coming is 
`{
  "test_array" : [ {
    "id" : 1
  }, {
    "id" : 2
  } ]
}`

Does the modifier operation doesn't support array traversal ? If it does then can someone please point out where I am doing this wrong.

**Comment by milosimpson** [comment]
Spec
```
[
  {
    "operation": "modify-overwrite-beta",
    "spec": {
      "test_array": {
        "[0]": {
          "id": 22
        }
      }
    }
  }
]
```

See test that exercises this for more examples.   https://github.com/bazaarvoice/jolt/blob/master/jolt-core/src/test/resources/json/modifier/arrayLiteral.json

Modify it very similar to Shift, but unlike shift needs to know that you mean for the "0" of test_array to actually be an array and not a string key of "0".

**Comment by dbgrey44** [comment]
Thanks a lot for the response. 

Also I was wondering if there is a current setup by which I can do sorting of a specific list based on a property in that list. For e.g. : 
`{"test_array":[ {"id":3}, {"id":2}], "test_array2": [{"id":3}, {"id":2}] }` and I wish to sort only on test_array that to based on id (assuming there are multiple properties in each element of list.

**Comment by milosimpson** [comment]
Nope, you will have to implement that yourself.

**Comment by bassa07** [comment]
How to make "modify-overwrite-beta" operation work for inner arrays as well?
Let's consider the above example when added an inner array and grand-inner array. 
1) In this case how to modify an inner/grand array using "modify-overwrite-beta" spec ?
2) When I'm trying to update a value in an outer array(there is no intentional update in an inner array), it is making inner array as an object and not considering further entries in it. weird response. but not sure how to consider an inner array as an escaped literal but not as part of a spec. I know excluding the inner array part in spec would give me the right response I needed. However, it doesn't solve my purpose because I still want to consider inner array as an object it self while modifying outer array value.

Input :

{
  "test_array": [
    {
      "id": 1,
      "inner_array": [
        {
          "iid": 11,
          "grand_inner_array": [
            {
              "gid": 111
            },
            {
              "gid": 112
            }
          ]
        },
        {
          "iid": 12,
          "grand_inner_array": [
            {
              "gid": 121
            },
            {
              "gid": 122
            }
          ]
        }
      ]
    },
    {
      "id": 2
    }
  ]
}

Spec:

[
  {
    "operation": "modify-overwrite-beta",
    "spec": {
      "test_array": {
        "[0]": {
          "id": 22,
          "inner_array": [
            {
              "iid": 11,
              "grand_inner_array": [
                {
                  "gid": 111
                },
                {
                  "gid": 112
                }
              ]
            },
            {
              "iid": 12,
              "grand_inner_array": [
                {
                  "gid": 121
                },
                {
                  "gid": 122
                }
              ]
            }
          ]
        }
      }
    }
  }
]

Received Response:

{
  "test_array" : [ {
    "id" : 22,
    "inner_array" : {
      "iid" : 11,
      "grand_inner_array" : [ {
        "gid" : 111
      }, {
        "gid" : 112
      } ]
    }
  }, {
    "id" : 2
  } ]
}

Expected Response:

{
  "test_array" : [ {
    "id" : 22,
    "inner_array" : [ {
      "iid" : 11,
      "grand_inner_array" : [ {
        "gid" : 111
      }, {
        "gid" : 112
      } ]
    }, {
      "iid" : 12,
      "grand_inner_array" : [ {
        "gid" : 121
      }, {
        "gid" : 122
      } ]
    } ]
  }, {
    "id" : 2
  } ]
}

I know that below spec would give me the desired result. However, considering the fact that when I'm trying to replace 0th element of the test_array then I may not end up checking if there is an inner array or grand inner array and so on in the input but just replace as is. is there any way that whatever has been supplied as a value for "[0]" is treated as input object but not a spec?

[
  {
    "operation": "modify-overwrite-beta",
    "spec": {
      "test_array": {
        "[0]": {
          "id": 22
        }
      }
    }
  }
]

**Comment by bassa07** [comment]
Another cool point I forgot to mention here is, when I update the grand_inner_array(let's say I updated the id from 111 to 1111) this way is getting updated properly. I mean, I see grand_inner_array as an array object with an updated value in it in the response. Not sure the random behavior with an inner_array here.

**Comment by milosimpson** [comment]
If you want to have "inner_array" have stuff defaulted on it then you need to tell it which indicies, like so.

Spec
```
[
  {
    "operation": "modify-overwrite-beta",
    "spec": {
      "test_array": {
        "[0]": {
          "id": 22,
          "inner_array": {
            "[0]": {
              "iid": 111111
            },
            "[1]": {
              "iid": 111222
            }
          }
        }
      }
    }
  }
]
```

**Comment by bassa07** [comment]
Thanks for your response. This answered my first question. 
However, I'm more interested to know more about my 2nd question.
Let me simplify the use case I'm trying to explain Q#2,

Use Case: My Rest endpoint receiving the first element of test_array as an updated JSON(it has inner arrays in it) and my spec is like a template and intended to replace the first element of test_array and this is not working as expected because the input has inner arrays and they are supposed to be replaced as the first element of the test_array.

```javascript
[
  {
    "operation": "modify-overwrite-beta",
    "spec": {
      "test_array": {
        "[0]": %s
      }
    }
  }
]
```
> is there any way to replace(as is) first element of test_array ? even if the input has inner/grand inner arrays in it but treat the entire string as an input and not look for the spec syntax as it has inner arrays in it.

Thanks you!!

**Comment by meisam94** [comment]
> If you want to have "inner_array" have stuff defaulted on it then you need to tell it which indicies, like so.
> 
> Spec
> 
> ```
> [
>   {
>     "operation": "modify-overwrite-beta",
>     "spec": {
>       "test_array": {
>         "[0]": {
>           "id": 22,
>           "inner_array": {
>             "[0]": {
>               "iid": 111111
>             },
>             "[1]": {
>               "iid": 111222
>             }
>           }
>         }
>       }
>     }
>   }
> ]
> ```


can you help me on this topic?
https://github.com/bazaarvoice/jolt/issues/1051
