### ISSUE TITLE
Add a new item in array using modifier

### ISSUE THREAD

**Issue by dbgrey44** [bazaarvoice/jolt#341]
I wanted to add some new elements at the end of array using some external context.
e.g. : 
`{a: [{"id":1},{"id":2}]}`

I want the new maps to be inserted at the end of array `a` using external context. 

Can anyone suggest the spec to do so ?

**Comment by milosimpson** [comment]
Doing stuff with the Context is not supported on the demo site.

I have not done the thing you want, aka add to an array given context.

I have a suggestion, instead of doing context and modify-default stuff, can you just "ninja" in the stuff you want to add directly into your input, and then use shift to "append" it to the array.

**Comment by milosimpson** [comment]
Example

Input
```
{
	"ninja": {
		"id": 3
	},
	"a": [
		{
			"id": 1
		},
		{
			"id": 2
		}
	]
}
```

Spec
```
[
  {
    "operation": "shift",
    "spec": {
      "a": "a",
      "ninja": "a[]"
    }
  }
]
```
Output
```
{
  "a" : [ {
    "id" : 1
  }, {
    "id" : 2
  }, {
    "id" : 3
  } ]
}
```

**Comment by dbgrey44** [comment]
Thanks for the info. From your example I got another thought; if a user wants to inject the objects at runtime based on the provided context, I think there is a way too.
He can first use modifier (definer) to add a similar "ninja" or any key not currently in the JSON object. And then shift it inside the corresponding array.

The main reason I was thinking of context was that the input JSON won't be dependent on adding the new section in existing JSON every-time.

That's just my thoughts. Let me know what your thoughts are.
