### ISSUE TITLE
Not suitable for high performance required service

### ISSUE THREAD

**Issue by houjincheng1992** [bazaarvoice/jolt#347]
First, I use jolt as part of my code for json transform, but finally I found that 3000QPS only 800~900 throughout, so may be not suitable for high performance required service. But it truly helpful for transforming json. 

So,  is there any official benchmark that can guide?

**Comment by Rajat0612** [comment]
I too wanted to use this library as part of a high performance transformation service and it'll be really helpful if someone can provide some official benchmarks. 

I tried out some cases and while the transformation itself is not too heavy, creating the objects by parsing the spec is. In my use case I have a set of specs, one of which can be chosen for transformation at runtime. 
Can anyone suggest how I can improve the performance ? (Maybe caching the objects and retrieving when processing input ? Will things like this lead to a significant performance improvement ?)

P.S : I can only spare a few milliseconds for transforming the JSON

**Comment by dbgrey44** [comment]
I too wanted to use this library as part of a high performance transformation service and it'll be really helpful if someone can provide some official benchmarks.

I tried out some cases and while the transformation itself is not too heavy, creating the objects by parsing the spec is. In my use case I have a set of specs, one of which can be chosen for transformation at runtime.
Can anyone suggest how I can improve the performance ? (Maybe caching the objects and retrieving when processing input ? Will things like this lead to a significant performance improvement ?)

P.S : I can only spare a few milliseconds for transforming the JSON

**Comment by milosimpson** [comment]
**How Bazaarvoice primarily uses Jolt**

The primary project at Bazaarvoice that utilizes Jolt is a Json Api project.   We get queries, build and execute backend ElasticSearch calls, get results, Transform the data, and return it.

Our run time is dominated by our ES query time, thus Jolt transform time is "very small" in comparison.

Each Api server typically handles 100 to 200 rps, and have have perf tested up to 400 rps.

Our Api is pretty "fat" in that it generates responses on the size of 50 kb uncompressed, where that data is pulled from 10 to 30 backend ElasticSearch calls.

"The transformation itself is not too heavy, creating the objects by parsing the spec is."
Yes, very much so.   We have about 15 spec files, and we cache the spec after it is loaded.    The stock transforms supplied by JOLT are safe to use in a multi-threaded environment / can be reused after spec parsing, I.E reuse the Chainr object built by loading a spec file.

**Tips for Speed**

- cache and re-use the Chainr objects after they have been built.
- avoid "*" matches with more than two "*" in them.   Eg. "tag-*-*" is fine as is processed "by hand" but "tag-*-*-*" falls back to a Java Regex matcher that is slow.

**If Jolt is still to Slow for you**

A) How much time is actually Jolt, vs JSON deserialization and serialization before and after Jolt runs?
B) "shift" is the only operation that makes copies of the data: "default", "cardinality", "remove", "modify-*-beta" and "sort" all operate on the supplied Java objects.   So you may still be able to use those operations to "do what they can" and then implement what you would have "shift" do for you by hand.

The reason shift "copies" data from the input to a new output map, because if it didn't it would be really easy to get ConcurrentModifcationExceptions, even when running in a Single thread.

**Comment by milosimpson** [comment]
See also https://github.com/bazaarvoice/jolt/issues/305 for more details on what Jolt is doing under the covers.

**Comment by houjincheng1992** [comment]
My config looks like the following, and I don't know whether it matter the result, and I'm looking for any other possible reasons.
[
      {
        "operation": "modify-overwrite-beta",
        "spec": {
          "rows": {
            "*": {
              "size": "=toInteger(@(1,size))",
              "version_code": "=toInteger(@(1,version_code))"

            }
          }
        }
      },
      {
        "operation": "shift",
        "spec": {
          "rows": {
            "*": {
              "apkmd5": "data[&1].signmd5",
              "package_name": "data[&1].pkg",
              "logo": "data[#2].logo.url",
              "game_img": {
                "*": "data[#3].images[].url"
              },
              "download_num": "data[&1].downloadNum",
              "game_banner": "data[&1].game_banner.url",
            }
          }
        }
      },
      {
        "operation": "default",
        "spec": {
          "data[]": {
            "*": {
              "logo": {
                "type": 1
              },
              "images[]": {
                "*": {
                  "type": 2
                }
              },
              "game_banner": {
                "type": 3
              }
            }
          }
        }
      },
      {
        "operation": "shift",
        "spec": {
          "data": {
            "*": {
              "logo": "data[&1].images[]",
              "game_banner": "data[&1].images[]",
              "images": {
                "*": "data[&2].images[]"
              },
              "*": "data[&1].&"
            }
          }
        }
      }
    ]

**Comment by milosimpson** [comment]
Need to seem some sample input.

The way to make it faster is to figure out a way to only do one shift.

Also, in your first shift, I don't think you mean to be using the "#".
```
              "logo": "data[#2].logo.url",
              "game_img": {
                "*": "data[#3].images[].url"
              },
```

**Comment by houjincheng1992** [comment]
Thanks a lot~
Input as the following:

```
{
	"rows": [
		{
			"logo": "logo-url",
			"apkmd5": "246b941",
			"package_name": "com.linekong.dbm.bd",
			"game_img": [
				"as_1.jpg",
				"as_2.jpg"
			],
			"download_num": 0,
			"game_banner": "banner-url"
		}
	],
	"total": 165,
	"res_code": 200
}


output sample:
{
  "data" : [ {
    "downloadNum" : 0,
    "images" : [ {
      "type" : 1,
      "url" : "logo-url"
    }, {
      "type" : 2,
      "url" : "as_1.jpg"
    }, {
      "type" : 2,
      "url" : "as_2.jpg"
    }, {
      "type" : 3,
      "url" : "banner-url"
    } ],
    "pkg" : "com.linekong.dbm.bd",
    "signmd5" : "246b941"
  } ]
}
```

**Comment by milosimpson** [comment]
A) "size" and "verison_code" don't seem to make it to the output, so you can drop the "modify" step that fixes them.

B)  Is it safe to say there will always be a "logo" and a "game_banner"?   If so can just always put those fields directly into an images array at index 0 and 1, an then default types for those things?

Spec
```
[
  {
    "operation": "shift",
    "spec": {
      "rows": {
        "*": {
          // easy renames
          "apkmd5": "data[&1].signmd5",
          "package_name": "data[&1].pkg",
          "download_num": "data[&1].downloadNum",
          
          // carefully build an images array
          "logo": "data[&1].images[0].url",
          "game_banner": "data[&1].images[1].url",
          "game_img": {
            // append the game_img urls to the images array
            //  after logo and game_banner have been dealt with
            "*": "data[&2].images[].url"
          }
        }
      }
    }
  },
  {
    "operation": "default",
    "spec": {
      "data[]": {
        "*": {
          "images[]": {
            "0": { // logo
              "type": 1
            },
            "1": { // game_banner
              "type": 3
            },
            "*": { // the rest
              "type": 2
            }
          }
        }
      }
    }
  }
]
```

Produces the same output as yours, but with the order of the images array being a little different.
