### ISSUE TITLE
How to override STOCK_TRANSFORMS

### ISSUE THREAD

**Issue by sunkarv** [bazaarvoice/jolt#406]
I am trying to write my own operation and trying to add to STOCK_TRANSFORMS, but it is static final.IS there any other way to do it?

**Comment by milosimpson** [comment]
No, there is specifically no way to add / override the STOCK_TRANSFORMS.    What I want to avoid is people asking questions here or on StackOverflow for things that they think are part of "standard" Jolt.

You can still name (package and Java Classname) your additional transform classes / operations nicely, so that the class name for them is "nice".

Ie.
```
{
    "operation" : "sunkarv.DateFix"  
    // instead of 
    "operation": "com.company.project.foo.jolt.transform.DateFix"
}
```
