### ISSUE TITLE
Stock functions/Date transformations for converting date/time formats

### ISSUE THREAD

**Issue by jashgala** [bazaarvoice/jolt#421]
I am working on a use case where I feel having JOLT transformations for converting date/time format would be very useful.
Example use cases would be - converting epoch time to dates and vice versa, YYYY-MM-DD HH:MM to DD-MM-YYYY or similar stuff.

Wanted to know whether adding Date functions is on the roadmap for this project as I can see there are some Math, String and List functions slowly being added.

Not sure if it is a feasible/valid use case as I haven't used JOLT a lot more than basic stuff, but would love to take a stab at contributing this if I can.

Thanks.

**Comment by milosimpson** [comment]
Yeah.   We implemented the Functions in the modify transform because we needed them, but I really don't like they way they work.   That and the complexity of Dates in Java in general, has had me gunshy about them.

The problem is Jolt operates on Object, so each function has to do all the type checking to see if it can actually do something.   We have a bit of a OO hierarchy to deal with it but it is a mess.

I would really like it to be easy to create functions.   I think I figured out the way to do that, effectively annotations and reflection.

That way you could register a class / function and annotate it with the type of each param you will accept, and the machinery of Jolt will either call your or not.

At that point it would be much saner to create Date conversion functions.

**Comment by jashgala** [comment]
Hi Milo, 

Any plans on implementing the new design you mentioned above and also in #644?

I am quite curious to see how it is done.

**Comment by ddcprg** [comment]
I'm looking into formatting a date value at the moment. I have something like "19991202" and want to transform it to "1999-12-02". Is there a way to do this at the moment?

**Comment by jashgala** [comment]
Ideally, you could write a class that defines a date format function for you... It is not supported out of the box in the library per se without using some form of voodoo magic with string splits and concats.
