### ISSUE TITLE
Help with inserting the value of one json into another.

### ISSUE THREAD

**Issue by pankajQW** [bazaarvoice/jolt#487]
This is the input :
```
{
  "response": [
    {
      "templateId": "59b901d592ec980b7716ba00",
      "formName": "Actual",
      "count": 1
    }
  ],
  "harcoded": [
    {
      "templateId": "59b901d592ec980b7716ba00",
      "formName": "Actual",
      "count": 0
    },
    {
      "templateId": "59b901d59211111111111111",
      "formName": "Planned",
      "count": 0
    }
  ]
}
```

and this is the expected output:
```
[
  {
    "templateId": "59b901d592ec980b7716ba00",
    "formName": "Planned",
    "count": 0
  },
  {
    "templateId": "59b901d59211111111111111",
    "formName": "Actual",
    "count": 1
  }
]
```

Logic is : output array should have two objects first is planned and second is actual (if input response array has the  planned/actual object then it should keep the count value of that object or put the 0 if not present and give array of two objects)

like if planned and actual both are not present then it should give array of two objects planned and actual both having count 0

Till now i have achieved this much : 
```
  [{
    "operation": "shift",
    "spec": {
      "response": {
        "*": { 
          "templateId": {
            "*": { 
              "@2": "templates.&1"
            }
          }
        }
      },
      "harcoded": "harcoded"
    }
  }, {
    "operation": "shift",
    "spec": {
      "harcoded": {
        "*": { 
          "templateId": {
            "*": {
              "@(4,templates.&)": {
                "$3": "@(4, harcoded)"
              }
            }
          }
        }
      }
    }
  }]
```

**Comment by krishadvani** [comment]
@milosimpson can you help us with this.

**Comment by milosimpson** [comment]
No.  A) I don't understand your problem, B) it sounds complicated enough that you should just write some code to do it.

**Comment by krishadvani** [comment]
@milosimpson The problem is that "response" is returned to us from the database, which comes up as empty in case there is nothing stored there. But the "response" can only be the one mentioned in the "hardcoded" section. 

So what we are trying to do is if the database responds empty, we want to place those dummy values instead rather than keeping an empty array.

Let us know if that is possible, or else we will just write code to transform it.

Thanks again.

**Comment by malhar-quickwork** [comment]
@milosimpson 
For the original input ,here is a spec tell me if its possible
```
 [{
  "operation": "shift",
  "spec": {
    "harcoded": {
      "*": {
        "templateId": {
          "@(3,response[&].templateId)": { //Match harcoded.templateId to response.templateId. Does this work?
               "@(4,response)": "output" // Return response object
          },
          "*": {
            "@2": "output" // Else return current harcoded object
          }
        }
      }
    }
  }
  }]
```

**Comment by milosimpson** [comment]
@krishadvani  see the Jolt Newbie follow on question on https://github.com/bazaarvoice/jolt/issues/481  

"The problem is that "response" is returned to us from the database, which comes up as empty in case there is nothing stored there."   

You can use the default operation, to fill in a value if nothing got back from the database, and then discriminate your transform based upon seeing the default value or not.
