### ISSUE TITLE
Integration with Spring MVC

### ISSUE THREAD

**Issue by rachalla** [bazaarvoice/jolt#570]
Like Jackson does automatic transformation of java objects at the spring mvc/rest controller method.
thereby we are agnostic of object to json transformation. 
Is it possible to smartly integrate jolt in between where we can configure spec.json and get the desired output, with minimum of code being seen.

**Comment by milosimpson** [comment]
I don't know what you are asking.

I will say that the Jar artifact structure of Jolt, was specifically designed so that the "core" transforms are as "pure" Java as possible.   

Hence, the "jolt-core.jar" has no Jackson, Dependency Injection, or CLI dependencies, specifically so that people can integrate it into their projects without "having to" deal with those dependencies if they don't want to.
