### ISSUE TITLE
Why the function  "doubleSubtract"'s result has so many  decimal places sometimes

### ISSUE THREAD

**Issue by niernier007** [bazaarvoice/jolt#695]
input :
{
  "table_two": [
    {
      "Hardware": 49.24
    }
  ]
}

spec:
  [{
      "operation": "shift",
      "spec": {
        "table_two": {
          "*": {
            "Hardware": "product_data[&1].discount"
          }
        }
      }
    }, {
      "operation": "modify-overwrite-beta",
      "spec": {
        "product_data": {
          "*": {
            "discount": "=doubleSubtract(@(1,discount),37.0)"
          }
        }
      }
}
]

output:
{
  "product_data" : [ {
    "discount" : 12.240000000000002
  } ]
}

I want to know why doubleSubtract sometimes returns the result that has so many  decimal places and sometimes  it is normal. For example, "discount": "=doubleSubtract(@(1,discount),17.0)"  will return 32.24.   How can i make it normal , i do not want so many decimal places.  Please help me.

**Comment by milosimpson** [comment]
Because doubles suck.   There is no dedicated "round" function.

Only thing that exists is "=divideAndRound", so use that in another modify and divide by 1.

See https://github.com/bazaarvoice/jolt/blob/master/jolt-core/src/test/resources/json/modifier/functions/mathTests.json  for examples of divideAndRound.

**Comment by niernier007** [comment]
@milosimpson Thank you so much.
