### ISSUE TITLE
Retain some json key value pairs while transforming them using jolt

### ISSUE THREAD

**Issue by mageshpandian91** [bazaarvoice/jolt#753]
I just started learning jolt. I want to transform a json to a desired format.

My input json looks like

```
{
      "first_name": {
        "label": "First name",
        "type": "text",
        "value": "John"
      },
      "last_name": {
        "label": "Last name",
        "type": "text",
        "value": "Doe"
      },
      "emails": {
        "label": "Emails",
        "type": "text",
        "value": "johndoe@gmail.com"
      },
      "facebook": {
        "label": "Facebook",
        "type": "text",
        "value": "test"
      },
      "twitter": {
        "label": "Twitter",
        "type": "text",
        "value": "test"
      },
      "linkedin": {
        "label": "LinkedIn",
        "type": "text",
        "value": "test"
      },
      "id": 123,
      "marital_status": "Single",
      "author_id": null,
      "company": null,
      "address": {
        "street": {
          "label": "street",
          "dom_type": "text",
          "value": "test"
        },
        "city": {
          "label": "city",
          "dom_type": "dropdown",
          "value": "test"
        },
        "state": {
          "label": "state",
          "dom_type": "dropdown",
          "value": "test"
        },
        "country": {
          "label": "country",
          "dom_type": "dropdown",
          "value": "test"
        }
      }
    }

```

to a format like this

```
 {
      "first_name" : "John",
      "last_name" : "Doe",
      "emails" : "johndoe@gmail.com",
      "facebook" : "test",
      "twitter" : "test",
      "linkedin" : "test",
      "id": 123,
      "marital_status": "Single",
      "author_id": null,
      "company": null,
      "address" : {
        "street" : "test",
        "city" : "test",
        "state" : "test",
        "country" : "test"
      }
    }
```

I have tried this spec 

 ```
[
      {
        "operation": "shift",
        "spec": {
          "address": {
            "*": {
              "@value": "address.&1"
            }
          },
          "*": {
            "@value": "&1"
          }
        }
      }
    ]

```
And got

```
{
      "first_name" : "John",
      "last_name" : "Doe",
      "emails" : "johndoe@gmail.com",
      "facebook" : "test",
      "twitter" : "test",
      "linkedin" : "test",
      "address" : {
        "street" : "test",
        "city" : "test",
        "state" : "test",
        "country" : "test"
      }
    }

```

Because the matcher "*" discards the simple key value pairs. I know that I'm missing something. Any help?

**Comment by milosimpson** [comment]
Because the matcher "*" discards the simple key value pairs. -> It isn't discarding them, it is matching them, but not finding a sub-property of "value".

Your input data is fundamentally in 3 different formats

1. Things below address
2. Things that are singular in value like "id"
3. Things that have nested data

The "*" just matches the Left-hand-side / key.

In this case you will need to explicitly list either the keys that are singular, or the keys that have nested data.

Spec

    [
      {
        "operation": "shift",
        "spec": {
          "address": {
            "*": {
              "@value": "address.&1"
            }
          },
          "id|marital_status|author_id|company": "&",
          "*": {
            "@value": "&1"
          }
        }
      }
    ]

**Comment by seshasaisrivatsav** [comment]
@milosimpson  Would you be able to let us know if JOLT is a good use case for large XML - JSON to JSON transformations?
Our spec files have over 10-15 operations and new engineers aren't able to understand the flow between each operation.

I'd like to know your thoughts on having large spec files and if Jolt is even worth our use case

**Comment by milosimpson** [comment]
What is the source of the complexity?   If it is inherit to the work that needs to be done and/or is it because of really stretching the OOTB transforms to avoid having to write any Java code / custom transforms?

When I was at BV, in the code base that used Jolt we wrote custom transforms, and for some "big" transforms wrote unit tests that validated / showed the incremental steps in the transform process. 


10 to 15 operations generally means two things.   

Option 1) The quantity of data (size of the Json is large) and the input & output are very different, meaning it is a complex or substantial transform.
Option 2) In an attempt to avoid writing any Java code, the stock transforms are getting applied many times.   Writing a custom transform may reduce the complexity.
Or both are true.

To help your new engineers, you may consider making unit tests that utilize Chainr's ability to run a subset of the tranform steps.

This being the very toy version 
https://github.com/bazaarvoice/jolt/blob/master/jolt-core/src/test/java/com/bazaarvoice/jolt/chainr/ChainrIncrementTest.java
https://github.com/bazaarvoice/jolt/tree/master/jolt-core/src/test/resources/json/chainr/increments

Cheers.

**Comment by seshasaisrivatsav** [comment]
@milosimpson  thanks for getting back. We have huge XML files, 10-30k lines. We convert them to JSON, 30k lines of JSON.
And they go through multiple json spec files. 
I believe it was done originally to avoid writing java code

We have 20-30 spec files. And each spec file has 10-20 operations in the array.
We are considering moving to XSLT. I'd like to get your thoughts on it.

**Comment by milosimpson** [comment]
> We are considering moving to XSLT. I'd like to get your thoughts on it.

Dunno.   Never "benchmarked" the performance or complexity of XSLT vs Jolt.    I had worked with XML and XSLT waaay back in the day, and did not like it.

I suspect that if you manage do everything in a single XSLT pass it would also be confusing.

**Comment by 9arnold** [comment]
Hi @milosimpson ,
I work with @seshasaisrivatsav , and we’d appreciate your guidance on whether Jolt is the right fit for our use case.

Context:

We convert hierarchical XML into JSON.
On top of the converted JSON, we apply Jolt transformations to produce the required outputs.
Our input consists of large JSON files with 5–6 different hierarchical structures and hundreds of repeating lists/segments.

Example (simplified):

`
{
  "Main": {
    "P1": {
      "P2": [
        {
          "D1": {
            "D2": [
              {
                "Type": "ABC",
                "D3": [
                  {
                    "Values": {
                      "Value": [
                        { "AttributeID": "attribute1", "content": "Hour" },
                        { "AttributeID": "attribute2", "content": 22.95 }
                      ]
                    }
                  },
                  {
                    "Values": {
                      "Value": [
                        { "AttributeID": "attribute1", "content": "Hour" },
                        { "AttributeID": "attribute2", "content": 22.95 }
                      ]
                    }
                  }
                ]
              }
            ]
          }
        }
       ]
    }
  }
`

Current Approach:

We use Jolt specs with conditional logic (e.g., "Type" == "ABC") and shift operations to flatten and restructure the JSON.
This works but is becoming increasingly complex as the number of variations grows.

Challenges:

Developers are finding it difficult to implement new transformations due to the complexity of Jolt specs.
Writing test cases for these large and deeply nested scenarios is also challenging.
Tools like ChatGPT and other platforms are not generating accurate Jolt specs for our use case, which adds to the difficulty.

Question:
Given the size, variability, and complexity of our JSON structures, do you think Jolt is still a suitable framework?

Handling large hierarchical JSON efficiently
Supporting conditional transformations
Maintaining scalability and testability

Your insights would be greatly appreciated.
