### ISSUE TITLE
Need help in converting array of string elements to an array of objects with some new properties.

### ISSUE THREAD

**Issue by kushagra-mahajan** [bazaarvoice/jolt#926]
So I have this input json :

`{
	"categories": ["Testing"]
}`

Now the expected output is 
`{
	"categories": [{
		"key1": "Testing",
		"key2": "",
		"key3": "",
		"key4": ""
	}]
}
`

Now if there were more than 1 element in the input json - the 2nd element will become the value of 2nd element.key1 in the output json and so on..

**Comment by zeshuai007** [comment]
Hi @kushagra-mahajan 
This is a common list to map, https://github.com/bazaarvoice/jolt/tree/master/jolt-core/src/test/resources/json/shiftr, there are many examples here that may be helpful to you.

I tried to do the conversion, but I'm not sure if it's what you expect, because I really don't understand key2-4, do they have any meaning?
E.g:
```
[
    {
        "operation": "shift",
        "spec": {
            "categories": {
                    "*":{
                    	"@":"categories.[&1].key1"
                    }
            }
        }
    },
    {
        "operation": "default",
        "spec": {
            "categories[]": {
                    "*":{
                    	"key4":"",
                    	"key3":"",
                    	"key2":""
                    }
            }
        }
    }
]
```

**Comment by kushagra-mahajan** [comment]
Thanks @zeshuai007  that worked what I was missing was categories[] in the default spec, guess I need to go through documentation and try some examples, just started on this one! Thanks a lot again! Closing this now!
